package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Lead struct{ID int64 `json:"id"`;Name string `json:"name"`;Company string `json:"company"`;Email string `json:"email"`;Stage string `json:"stage"`;ValueCents int64 `json:"value_cents"`;Notes string `json:"notes"`;FollowUpDate string `json:"follow_up_date"`;Won *bool `json:"won"`;CreatedAt time.Time `json:"created_at"`;UpdatedAt time.Time `json:"updated_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"prospector.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS leads(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,company TEXT DEFAULT '',email TEXT DEFAULT '',stage TEXT DEFAULT 'prospect',value_cents INTEGER DEFAULT 0,notes TEXT DEFAULT '',follow_up_date TEXT DEFAULT '',won INTEGER,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)Create(l *Lead)error{res,err:=db.Exec(`INSERT INTO leads(name,company,email,stage,value_cents,notes,follow_up_date)VALUES(?,?,?,?,?,?,?)`,l.Name,l.Company,l.Email,l.Stage,l.ValueCents,l.Notes,l.FollowUpDate);if err!=nil{return err};l.ID,_=res.LastInsertId();return nil}
func(db *DB)List(stage string)([]Lead,error){q:=`SELECT id,name,company,email,stage,value_cents,notes,follow_up_date,won,created_at,updated_at FROM leads WHERE 1=1`;args:=[]interface{}{};if stage!=""{q+=` AND stage=?`;args=append(args,stage)};q+=` ORDER BY updated_at DESC`;rows,err:=db.Query(q,args...);if err!=nil{return nil,err};defer rows.Close();var out[]Lead;for rows.Next(){var l Lead;var won *int;rows.Scan(&l.ID,&l.Name,&l.Company,&l.Email,&l.Stage,&l.ValueCents,&l.Notes,&l.FollowUpDate,&won,&l.CreatedAt,&l.UpdatedAt);if won!=nil{v:=*won==1;l.Won=&v};out=append(out,l)};return out,nil}
func(db *DB)Update(l *Lead){db.Exec(`UPDATE leads SET name=?,company=?,email=?,stage=?,value_cents=?,notes=?,follow_up_date=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,l.Name,l.Company,l.Email,l.Stage,l.ValueCents,l.Notes,l.FollowUpDate,l.ID)}
func(db *DB)CloseLead(id int64,won bool){w:=0;if won{w=1};db.Exec(`UPDATE leads SET stage='closed',won=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,w,id)}
func(db *DB)Delete(id int64){db.Exec(`DELETE FROM leads WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var total,won int;var pipeline int64;db.QueryRow(`SELECT COUNT(*) FROM leads WHERE stage!='closed'`).Scan(&total);db.QueryRow(`SELECT COUNT(*) FROM leads WHERE won=1`).Scan(&won);db.QueryRow(`SELECT COALESCE(SUM(value_cents),0) FROM leads WHERE stage!='closed'`).Scan(&pipeline);return map[string]interface{}{"open_leads":total,"won_deals":won,"pipeline_cents":pipeline},nil}
